/**
 * @file license/installation.ts
 * @description Installation management for the Volqan licensing system.
 *
 * An "installation" is a unique Volqan deployment identified by an installation
 * ID. Installations can be linked to a paid subscription to unlock features
 * like attribution removal.
 *
 * Installation IDs are generated by the framework's license/checker.ts and
 * stored in the VOLQAN_INSTALL_ID environment variable.
 */
export interface Installation {
    /** Unique installation identifier (e.g. "vi_abc123..."). */
    installationId: string;
    /** Primary domain this installation serves (e.g. "example.com"). */
    domain: string;
    /** ID of the linked subscription, if any. null for unlicensed installs. */
    subscriptionId: string | null;
    /** When the installation was first registered (UTC). */
    registeredAt: Date;
    /** Whether this installation has passed integrity checks. */
    isValidated: boolean;
}
/**
 * Persistence interface for Installation records.
 * Implement against your database.
 */
export interface InstallationStore {
    /**
     * Find an installation by its ID.
     * Returns null if not found.
     */
    findByInstallationId(installationId: string): Promise<Installation | null>;
    /**
     * Create a new installation record or return the existing one if the
     * installationId is already registered (upsert semantics).
     */
    upsertInstallation(data: {
        installationId: string;
        domain: string;
    }): Promise<Installation>;
    /**
     * Link an installation to a paid subscription.
     */
    linkToSubscription(installationId: string, subscriptionId: string): Promise<Installation>;
    /**
     * Unlink an installation from its current subscription.
     */
    unlinkSubscription(installationId: string): Promise<Installation>;
    /**
     * Mark an installation as validated (or invalidated).
     */
    setValidated(installationId: string, isValidated: boolean): Promise<Installation>;
}
/**
 * Register a new installation or update an existing one.
 *
 * Called when a Volqan instance first starts up and contacts the license API.
 *
 * @param store          - Installation store implementation.
 * @param domain         - Primary domain of the installation.
 * @param installationId - The installation's unique identifier.
 * @returns The Installation record.
 */
export declare function registerInstallation(store: InstallationStore, domain: string, installationId: string): Promise<Installation>;
/**
 * Retrieve an installation by its ID.
 *
 * @param store          - Installation store implementation.
 * @param installationId - The installation's unique identifier.
 * @returns The Installation record, or null if not found.
 */
export declare function getInstallation(store: InstallationStore, installationId: string): Promise<Installation | null>;
/**
 * Link an installation to a paid subscription.
 *
 * This associates the installation with a subscription so license checks
 * can return the correct entitlements.
 *
 * @param store          - Installation store implementation.
 * @param installationId - The installation's unique identifier.
 * @param subscriptionId - The internal subscription ID to link.
 * @returns The updated Installation record.
 */
export declare function linkToSubscription(store: InstallationStore, installationId: string, subscriptionId: string): Promise<Installation>;
/**
 * Remove the subscription link from an installation.
 *
 * Called when a subscription is cancelled or transferred.
 *
 * @param store          - Installation store implementation.
 * @param installationId - The installation's unique identifier.
 * @returns The updated Installation record.
 */
export declare function unlinkSubscription(store: InstallationStore, installationId: string): Promise<Installation>;
/**
 * Validate that an installation is legitimate.
 *
 * Basic validation checks:
 * - The installation ID follows the expected format (vi_ prefix + 24 hex chars).
 * - The installation exists in the database.
 * - The domain is not on a blocklist.
 *
 * @param store          - Installation store implementation.
 * @param installationId - The installation's unique identifier.
 * @returns true if the installation is legitimate.
 */
export declare function validateInstallation(store: InstallationStore, installationId: string): Promise<boolean>;
/**
 * Check if an installation ID follows the expected format.
 *
 * Valid formats:
 *   vi_<24 lowercase hex chars>          (deterministic hash)
 *   vi_<24 lowercase hex chars>          (random fallback)
 *
 * @param id - The installation ID to validate.
 * @returns true if the format is valid.
 */
export declare function isValidInstallationIdFormat(id: string): boolean;
//# sourceMappingURL=installation.d.ts.map